---
ID: "2da70f91-35fa-416c-b07b-004b8ec9d81e"
Parent: "9009b31e-a511-47f9-9794-d8bea68daae4"
Template: "ab987746-78b0-4773-a8de-b295c493b7a4"
Path: /sitecore/content/vmldemo/vmldemo/Settings/Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241028T123638Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9c50ca2f-25cd-4e27-9ee5-e1d53fd6fb29"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241028T123638Z
