---
ID: "b3bbc567-b0c9-471e-bf52-9e1e9c72a8a9"
Parent: "c1e067ee-3bc8-4eb2-bb36-f1cfca524bf1"
Template: "c1e067ee-3bc8-4eb2-bb36-f1cfca524bf1"
Path: /sitecore/templates/Feature/vmldemo/Header/Header/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{22492B74-CB39-41CF-B079-3421DC8E4DA1}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241030T091013Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ba8f0ed3-650d-49c4-aa30-ba655df28cb8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241030T091045Z
